# Generated by Django 4.0.4 on 2022-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
